---
apiVersion: v1
kind: Namespace
metadata:
  name: dynamic-configuration-system
  labels:
    app.kubernetes.io/part-of: dynamic-configuration
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamic-configuration-operator
  namespace: dynamic-configuration-system
  labels:
    app.kubernetes.io/name: dynamic-configuration-operator
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: dynamic-configuration
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: dynamic-configuration-operator
      app.kubernetes.io/component: operator
      app.kubernetes.io/part-of: dynamic-configuration
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/name: dynamic-configuration-operator
        app.kubernetes.io/component: operator
        app.kubernetes.io/part-of: dynamic-configuration
    spec:
      containers:
      - name: manager
        image: controller
        command:
        - /manager
        args:
        - --leader-elect
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 50m
            memory: 64Mi
          requests:
            cpu: 10m
            memory: 32Mi
      serviceAccountName: dynamic-configuration-operator
      securityContext:
        runAsNonRoot: true
      terminationGracePeriodSeconds: 10
