---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dynamic-configuration-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dynamic-configuration-operator
subjects:
- kind: ServiceAccount
  name: dynamic-configuration-operator
  namespace: dynamic-configuration-system
